### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by deanie77** [Bvudzijena/school-system#1]
could you provide good documentation so that we have a clear plan on how to collaborate.

**Comment by Bvudzijena** [comment]
[Major Project Object-Oriented Programming.pdf](https://github.com/Bvudzijena/school-system/files/7667091/Major.Project.Object-Oriented.Programming.pdf)

**Comment by deanie77** [comment]
Thank you for the documentation its very clear @Bvudzijena
